"""`onchain.kind = "semantos-cell"` — Trinote's half of a semantos-published anchor.

Two things are being tested, and only one of them is about this file's code.

The first is ordinary: a bundle can carry evidence of a cell semantos published, the
verifier binds it to the receipt sitting beside it, and a substituted receipt is caught.

The second is the cross-language contract. `evidence_commit` here and `evidenceCommit()`
in the semantos cartridge must produce identical digests for identical objects and
refuse identical inputs *with the same reason code*. The vectors in
`vectors/semantos-cell.vectors.json` were generated by running the TypeScript, so a
passing run means the two implementations agree — not that this one is self-consistent.
"""
from __future__ import annotations

import json
import pathlib

import pytest

from trinote.bundle.pack import pack_bundle, BundleError
from trinote.bundle.semantos_cell import (
    EVIDENCE_KIND,
    EvidenceError,
    evidence_binds_receipt,
    evidence_commit,
    evidence_bytes,
    is_confirmed,
    validate_evidence,
)
from trinote.bundle.verify import verify_bundle
from trinote.receipts.receipt import build_receipt
from trinote.receipts.signing_ec import ec_keygen

VECTORS = json.loads(
    (pathlib.Path(__file__).parent / "vectors" / "semantos-cell.vectors.json").read_text()
)

H = lambda b: b * 64                                        # noqa: E731


def _evidence(receipt_hash: str, **over):
    e = {"kind": EVIDENCE_KIND, "txid": H("1"), "vout": 0, "cellHash": H("2"),
         "typeHash": H("3"), "receiptHash": receipt_hash, "modelBindingHash": H("5"),
         "inclusionProofRef": None}
    e.update(over)
    return e


def _bundle():
    model, cp = ec_keygen(label="m"), ec_keygen(label="c")
    return build_receipt(model_hash=H("a"), input_ids=[1, 2], output_ids=[3],
                         sampler={"mode": "greedy"}, model_key=model, counterparty_key=cp,
                         schema_version="v3", context_commit=H("c"))


# ------------------------------------------------ the contract with the other language

@pytest.mark.parametrize("case", VECTORS["accept"], ids=lambda c: c["name"])
def test_accepted_evidence_commits_to_what_typescript_committed(case):
    assert evidence_commit(case["evidence"]) == case["evidenceCommit"]


@pytest.mark.parametrize("case", VECTORS["accept"], ids=lambda c: c["name"])
def test_the_canonical_bytes_are_identical_not_merely_the_digest(case):
    """A matching digest with different bytes would mean a collision, so this is the
    check that actually says the encoders agree."""
    assert evidence_bytes(case["evidence"]).decode() == case["canonical"]


@pytest.mark.parametrize("case", VECTORS["reject"], ids=lambda c: c["name"])
def test_refusals_agree_on_the_reason_not_only_on_refusing(case):
    with pytest.raises(EvidenceError) as exc:
        evidence_commit(case["evidence"])
    assert exc.value.code == case["reason"]


def test_the_vector_file_covers_both_outcomes():
    # a suite that lost its reject half would still pass every test above
    assert len(VECTORS["accept"]) >= 5 and len(VECTORS["reject"]) >= 8


# ------------------------------------------------------------- broadcast vs inclusion

def test_a_broadcast_is_not_an_inclusion():
    submitted = _evidence(H("4"))
    confirmed = _evidence(H("4"), inclusionProofRef="beef:0001")
    assert is_confirmed(submitted) is False
    assert is_confirmed(confirmed) is True


def test_an_empty_proof_reference_is_not_a_second_spelling_of_absent():
    with pytest.raises(EvidenceError) as exc:
        validate_evidence(_evidence(H("4"), inclusionProofRef=""))
    assert exc.value.code == "bad-length"


# ------------------------------------------------------------------ binding a receipt

def test_evidence_binds_the_receipt_it_names():
    e = _evidence(H("4"))
    assert evidence_binds_receipt(e, H("4")) is True
    assert evidence_binds_receipt(e, H("9")) is False


def test_the_model_binding_is_checked_when_the_caller_knows_it():
    e = _evidence(H("4"), modelBindingHash=H("5"))
    assert evidence_binds_receipt(e, H("4"), H("5")) is True
    assert evidence_binds_receipt(e, H("4"), H("7")) is False


# ------------------------------------------------------------------- through a bundle

def test_a_bundle_carries_the_evidence_and_verifies_offline(tmp_path):
    b = _bundle()
    rh = b["receipt"]["receiptHash"]
    info = pack_bundle(bundle=b, onchain=_evidence(rh), out_dir=tmp_path / "bundle")
    assert info["manifest"]["kind"] == EVIDENCE_KIND

    res = verify_bundle(tmp_path / "bundle")
    named = {c["check"]: c for c in res["offline"]["checks"]}
    assert named["semantosCell.wellFormed"]["ok"] is True
    assert named["semantosCell.receiptHash"]["ok"] is True
    assert "submitted" in named["semantosCell.anchorState"]["detail"]


def test_a_confirmed_bundle_says_so(tmp_path):
    b = _bundle()
    rh = b["receipt"]["receiptHash"]
    pack_bundle(bundle=b, onchain=_evidence(rh, inclusionProofRef="beef:0001"),
                out_dir=tmp_path / "bundle")
    res = verify_bundle(tmp_path / "bundle")
    named = {c["check"]: c for c in res["offline"]["checks"]}
    assert "confirmed" in named["semantosCell.anchorState"]["detail"]


def test_evidence_for_a_different_receipt_is_refused_at_pack_time(tmp_path):
    """Caught here rather than at verify: by the time a verifier rejects the bundle the
    anchor has been paid for, and the rejection cannot say which field was wrong."""
    b = _bundle()
    with pytest.raises(BundleError, match="different receipt"):
        pack_bundle(bundle=b, onchain=_evidence(H("9")), out_dir=tmp_path / "bundle")


def test_malformed_evidence_never_reaches_a_bundle(tmp_path):
    b = _bundle()
    bad = _evidence(b["receipt"]["receiptHash"])
    bad["vout"] = -1
    with pytest.raises(BundleError, match="malformed"):
        pack_bundle(bundle=b, onchain=bad, out_dir=tmp_path / "bundle")


def test_a_substituted_receipt_breaks_the_binding_at_verify(tmp_path):
    """The bundle's own hash checks catch the swap; this asserts the semantos-cell
    binding is not somehow satisfied by a receipt it does not name."""
    b = _bundle()
    rh = b["receipt"]["receiptHash"]
    root = tmp_path / "bundle"
    pack_bundle(bundle=b, onchain=_evidence(rh), out_dir=root)

    other = _bundle()
    (root / "receipt.json").write_bytes(
        json.dumps(other["receipt"], sort_keys=True, separators=(",", ":")).encode())

    res = verify_bundle(root)
    assert res["ok"] is False
